# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/litedash
  docker:
    - image: circleci/node:10.16.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing packages
          command: yarn install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/litedash
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/litedash
      - run:
          name: Setup release directory
          command: |
            rm -rf $RELEASE_DIR
            mkdir $RELEASE_DIR
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > "~/litedash/$RELEASE_DIR/.npmrc"
      - run:
          name: Publish package
          command: "PUBLISH_DIR=$RELEASE_DIR npm publish ${PUBLISH_DIR}"

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/